name: Update caddy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Get latest caddy
      id: caddy-version
      shell: bash
      run: |
        export TOKEN=$(curl -fsSL "https://auth.docker.io/token?service=registry.docker.io&scope=repository:library/caddy:pull" | jq --raw-output '.token')
        export CREATED=$(curl -fsSL -H "Authorization: Bearer $TOKEN" "https://registry.hub.docker.com/v2/library/caddy/manifests/builder" | jq .history[0].v1Compatibility -r | jq --raw-output '.created')
        export ITEMS=$(curl -fsSL -H "Authorization: Bearer $TOKEN" "https://registry.hub.docker.com/v2/library/caddy/manifests/builder" | jq .history[0].v1Compatibility -r | jq ".config.Env | .[]" -r)
        for x in $ITEMS; do if [[ "$x" == CADDY_VERSION=* ]]; then export "$x"; fi done
        echo ::set-output name=latest_version::$CADDY_VERSION
        echo ::set-output name=current_version::$(<caddy.version)
        echo ::set-output name=latest_created::$CREATED
        echo ::set-output name=current_created::$(<caddy.created)
        
    - name: Update caddy version file, commit and push
      if: steps.caddy-version.outputs.current_created != steps.caddy-version.outputs.latest_created
      run: |
        git config --global user.name 'Shaddy'
        git config --global user.email 'shaddythefirst@gmail.com'
        echo ${{ steps.caddy-version.outputs.latest_version }} > caddy.version
        echo ${{ steps.caddy-version.outputs.latest_created }} > caddy.created
        git add .
        git commit -am "Automated update to ${{ steps.caddy-version.outputs.latest_version }}"
        git push
        
    - name: Update tag
      if: steps.caddy-version.outputs.current_version != steps.caddy-version.outputs.latest_version
      run: |
        git config --global user.name 'Shaddy'
        git config --global user.email 'shaddythefirst@gmail.com'
        git tag ${{ steps.caddy-version.outputs.latest_version }}
        git push --tags
